Jrlegrand/30/filters
coderxio/dailymed-api pull request #35
Opened 2020-09-29 19:53 UTC by jrlegrand

Fixes coderxio/dailymed-api#30, fixes coderxio/dailymed-api#34

## Explanation
Added Django Filters functionality for SPL view and made the SPL view distinct.

## Rationale
So users can filter down to only the SPLs they care about.  Alternatives considered were using GraphQL-type functionality, which we may implement later on.

## Tests
1. Tested out different filters and discovered a duplication bug which was also fixed as part of this PR

2020-09-29 19:58 UTC, finish06 commented
@jrlegrand Would you like to fix the styling errors or would you like me to do it?
```
0.53s$ flake8
./api/dailymed/filters.py:4:1: E302 expected 2 blank lines, found 1
./api/dailymed/filters.py:7:80: E501 line too long (100 > 79 characters)
./api/dailymed/filters.py:8:80: E501 line too long (90 > 79 characters)
./api/dailymed/filters.py:9:80: E501 line too long (91 > 79 characters)
./api/dailymed/filters.py:10:80: E501 line too long (125 > 79 characters)
./api/dailymed/filters.py:11:80: E501 line too long (125 > 79 characters)
./api/dailymed/filters.py:12:80: E501 line too long (88 > 79 characters)
./api/dailymed/views.py:11:1: E302 expected 2 blank lines, found 1
```

2020-09-30 00:50 UTC, jrlegrand commented
I'll give it a shot tomorrow morning.

2020-09-30 15:23 UTC, finish06 commented
@jrlegrand Two pending styling errors:
```
$ flake8
./api/dailymed/filters.py:13:1: E302 expected 2 blank lines, found 1
./api/dailymed/filters.py:27:37: W291 trailing whitespace
```

2020-09-30 15:25 UTC, finish06 requested changes

2020-09-30 15:25 UTC, finish06 commented on api/dailymed/filters.py
> +
Add another line break.

2020-09-30 15:25 UTC, finish06 commented on api/dailymed/filters.py
> +        field_name='products__code',
Remove white space after `,`

2020-09-30 15:39 UTC, finish06 approved these changes
Ran Flake8 locally on pull.  Everything looks good.

2020-09-30 15:49 UTC, merged